package it.unibo.michelito.controller.objectsadapter;

import it.unibo.michelito.controller.levelgenerator.LevelGenerator;
import it.unibo.michelito.controller.objectsadapter.impl.ObjectsAdapterImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Test for the {@link ObjectsAdapterImpl} class.
 */
final class TestObjectsAdapter {
    private ObjectsAdapterImpl objectsAdapter;

    @BeforeEach
    void setUp() {
        objectsAdapter = new ObjectsAdapterImpl();
    }

    /**
     * Test if the objectsAdapter return a set of the same size
     * of the one generated by {@link LevelGenerator}.
     */
    @Test
    void testGetObjects() {
        final var levelGeneratorSet = LevelGenerator.generate(LevelGenerator.testLevel());
        final var objectsAdapterSet = objectsAdapter.requestMazeObjects(LevelGenerator.testLevel());
        assertEquals(levelGeneratorSet.size(), objectsAdapterSet.size());
    }
}
